Upipe/upipe

- lib/upipe-modules/upipe_rtp_prepend.c
> upipe_rtp_prepend: set a default 90k clock rate

- include/upipe/ubuf_pic.h
- include/upipe/uref_pic.h
- lib/upipe-modules/upipe_blank_source.c
- lib/upipe-swscale/upipe_sws_thumbs.c
- lib/upipe/ubuf_pic.c
- tests/ubuf_pic_mem_test.c
> ubuf_clear: Add support for tvrange/fullrange clearing of Y-plane

- lib/upipe-av/upipe_avformat_source.c
Use av_guess_sample_aspect_ratio() to extract the stream-specific aspect
ratio in addition to the aspect ratio from the codec context.
> upipe-av: improve aspect ratio detection

- include/upipe/Makefile.am
- include/upipe/uprobe_loglevel.h
- lib/upipe/Makefile.am
- lib/upipe/uprobe_loglevel.c
This probe lets you change the log level depending on the message tags.
> add uprobe_loglevel

- include/upipe-alsa/Makefile.am
- include/upipe-alsa/upipe_alsa_source.h
- lib/upipe-alsa/Makefile.am
- lib/upipe-alsa/upipe_alsa_source.c
- lib/upipe-modules/upipe_rtp_prepend.c
Note this requires a bitstream patch
> Add simple ALSA in stereo support and Opus in RTP output

- include/upipe/ubase.h
- lib/upipe-framers/upipe_h264_framer.c
Ok I think this is the right one...
> h264_framer: Reject invalid cpb_cnt

- examples/uplay.c
- include/upipe-modules/Makefile.am
- include/upipe-modules/upipe_blit.h
- include/upipe-modules/upipe_subpic_schedule.h
- include/upipe/ubuf_pic.h
- include/upipe/uref_pic.h
- lib/upipe-av/upipe_avcodec_decode.c
- lib/upipe-modules/Makefile.am
- lib/upipe-modules/upipe_blit.c
- lib/upipe-modules/upipe_subpic_schedule.c
Here's an updated version of subpic schedule.
Unadressed comments:
- https://github.com/funman/upipe/commit/db61123757fbe696b86ce508130d5604624c5fef#commitcomment-18472199
- Missing unit test
> Sub schedule

- Makefile.am
- configure.ac
- lib/upipe-blackmagic/Makefile.am
Fix build with --disable-shared
> Disable shared

- lib/upipe-blackmagic/upipe_blackmagic_source.cpp
fix memory leaks detected with valgrind --undef-value-errors=no --leak-check=full
> Bmdsrc leak

- lib/upipe-modules/upipe_rtp_prepend.c
https://tools.ietf.org/html/rfc2250#section-3.5
> rtp_prepend: fix mpa payload

- lib/upipe-v210/upipe_v210enc.c
Ask for 10 bit if input is has a y10l plane, else 8 bit
> v210enc: provides flow_format

- lib/upipe-modules/upipe_blit.c
We avoid doing a ubuf_pic_copy if the picture is still used by avcodec
> blit: do not map uref if there is nothing to blit

- configure.ac
- include/Makefile.am
- include/upipe-netmap/Makefile.am
- include/upipe-netmap/upipe_netmap_source.h
- lib/Makefile.am
- lib/upipe-netmap/Makefile.am
- lib/upipe-netmap/libupipe_netmap.pc.in
- lib/upipe-netmap/upipe_netmap_source.c
> netmap source pipe

- lib/upipe-framers/upipe_mpgv_framer.c
depends on https://code.videolan.org/videolan/bitstream/merge_requests/7
> mpgv framer: add max rate limits for multi-view/422 profiles

- lib/upipe-modules/upipe_udp_sink.c
> udp_sink: fix 168a19d96dea1255cf05cdf0643b272c5e4aefc2

- lib/upipe-filters/Makefile.am
> Fix compilation if bitstream is missing

- lib/upipe-ts/upipe_ts_demux.c
This fixes a PMT update with a PID going from video to audio for example
> ts_demux: check if ES have changed on PMT update

- lib/upipe-ts/upipe_ts_demux.c
This fixes the SDT attributes randomly failing to appear
> ts_demux: use setflowdef to give SDT attributes to PMT

- lib/upipe-blackmagic/upipe_blackmagic_source.cpp
Use passthrough=MODE option to specify the capture passthrough mode for
the decklink device.
Available modes:
- disabled: no passthough
- direct: electrical connection
- clean_switch: playback captured video
By default, the passthrough mode is left unconfigured, to allow changing
it from an external process.
> bmd_src: add passthrough configuration

- include/upipe-dveo/Makefile.am
- include/upipe-dveo/upipe_dveo_asi_sink.h
- lib/upipe-dveo/Makefile.am
- lib/upipe-dveo/asi_ioctl.h
- lib/upipe-dveo/upipe_dveo_asi_sink.c
This is an RFC.
Currently missing: 
- latency handling
- scope testing to make sure output rate is correct after dejittering input stream
- maybe options handling (buffers/bufsize)
- maybe another way to open the card (wait until first packet is received?)
Comments welcome!
> DVEO ASI sink

- .travis.yml
Attempt to fix failure to install libpng-dev on i386
> travis: fix apt-get failure

- lib/upipe-modules/upipe_htons.c
POSIX requires non overlapping swab buffers: "If copying takes place
between objects that overlap, the behavior is undefined."
> upipe_htons: don't use swab

- lib/upipe-av/upipe_avcodec_decode.c
Don't hardcode alignment. 16 is not enough for AVX.
> upipe-av: fix decoder frame alignment

- include/upipe-framers/Makefile.am
- include/upipe-framers/upipe_s337_framer.h
- lib/upipe-framers/Makefile.am
- lib/upipe-framers/upipe_s337_framer.c
This pipe takes sound.s32. with s337 data and outputs complete s337 frames,
starting with the header
> New pipe: s337 framer

- configure.ac
- lib/upipe-hbrmt/Makefile.am
- lib/upipe-hbrmt/upipe_pack10bit.c
- lib/upipe-hbrmt/upipe_unpack10bit.c
- lib/upipe-v210/Makefile.am
- lib/upipe-v210/upipe_v210dec.c
- lib/upipe-v210/upipe_v210enc.c
I thought this was a good idea to reduce the changes I need to do to add checkasm.
> Change x86 assembler define for the C preprocessor

- include/upipe-modules/Makefile.am
- include/upipe-modules/upipe_block_to_sound.h
- lib/upipe-modules/Makefile.am
- lib/upipe-modules/upipe_block_to_sound.c
- tests/Makefile.am
- tests/upipe_block_to_sound_test.c
Created a module to convert block urefs to sound urefs and pass them on.
> Block to sound

- lib/upipe-hbrmt/Makefile.am
- lib/upipe-hbrmt/sdidec.c
- lib/upipe-hbrmt/sdidec.h
- lib/upipe-hbrmt/sdienc.c
- lib/upipe-hbrmt/sdienc.h
- lib/upipe-hbrmt/upipe_pack10bit.c
- lib/upipe-hbrmt/upipe_unpack10bit.c
- lib/upipe-v210/Makefile.am
- lib/upipe-v210/upipe_v210dec.c
- lib/upipe-v210/upipe_v210enc.c
- lib/upipe-v210/v210dec.c
- lib/upipe-v210/v210dec.h
- lib/upipe-v210/v210enc.c
- lib/upipe-v210/v210enc.h
At the request of @nto I have cherry-picked these commits from the checkasm pull request.
> Move some C functions into dedicated files

- include/upipe-filters/upipe_zoneplate_source.h
- include/upipe-freetype/upipe_freetype.h
- include/upipe-modules/upipe_aes_decrypt.h
- include/upipe-modules/upipe_audio_blank.h
- include/upipe-modules/upipe_grid.h
- include/upipe-modules/upipe_subpic_schedule.h
- include/upipe-modules/upipe_void_source.h
- include/upipe/udict.h
- include/upipe/uprobe_ubuf_mem.h
- include/upipe/uprobe_ubuf_mem_pool.h
- include/upipe/uprobe_uclock.h
- include/upipe/uprobe_uref_mgr.h
- include/upump-ecore/upump_ecore.h
- include/upump-ev/upump_ev.h
Note that I placed '#ifdef __cplusplus' after '#include' directives because I consider that each header file takes care of itself.
By the way, Happy new year !
> Add extern C to public headers

- lib/upipe-alsa/upipe_alsa_sink.c
This reverts commit 30d785c64561b8dbd6248f7a62891aeb7978709f.
This doesn't make virtualbox work better but it makes things worse on my setup:
Intel Corporation 7 Series/C216 Chipset Family High Definition Audio Controller
> Revert "attempt at fixing alsa sink"

- lib/upipe-ts/upipe_ts_demux.c
Bug introduced in 424c529c7c1490c12056dccb2d2620a9810702ff
> ts_demux: fix restart of ES on PMT change

- doc/overview.mkdoc
- include/upipe-modules/Makefile.am
- include/upipe-modules/upipe_audio_copy.h
- lib/upipe-modules/Makefile.am
- lib/upipe-modules/upipe_audio_copy.c
- tests/Makefile.am
- tests/upipe_audio_copy_test.c
This pipe outputs fixed size sound buffers.
> upipe_audio_copy: add an audio copy pipe

- lib/upipe-av/upipe_avcodec_decode.c
- lib/upipe-modules/upipe_subpic_schedule.c
They will replace the previous subtitle with a transparent region
> teletext fixes

- lib/upipe-gl/upipe_gl_sink_common.c
> gl_sink: respect stride

- lib/upipe-alsa/upipe_alsa_source.c
it needs to be set before opening the device
Note #459 is no longer needed with this
> alsa: add an option to set the capture period

- lib/upipe-filters/upipe_rtp_feedback.c
we would not be duplicating the flow_def we receive before storing it
> rtpfb: fix set_flow_def

- examples/arq_rx.c
- examples/arq_tx.c
- include/upipe-filters/upipe_rtcp_fb_receiver.h
- include/upipe-filters/upipe_rtp_feedback.h
- lib/upipe-filters/upipe_rtcp_fb_receiver.c
- lib/upipe-filters/upipe_rtp_feedback.c
With a bit of work on RTCP, we might be able to interop with gstreamer (untested so far)
> ARQ: use rfc3611 and rfc4588

- lib/upipe-ts/upipe_rtp_fec.c
Mainly helps if reorder pipe is placed in front of FEC
> rtp_fec: Add various improvements

- lib/upipe-freetype/upipe_freetype.c
index value 0 is valid and will display a box for missing characters
> freetype: unicode support

- include/upipe-modules/Makefile.am
- include/upipe-modules/upipe_row_join.h
- lib/upipe-modules/Makefile.am
- lib/upipe-modules/upipe_row_join.c
- tests/Makefile.am
- tests/upipe_row_join_test.c
This adds a new pipe to join chunks into a new picture.  It does the reverse operation of row_split that @funman wants to add in PR #485.
I do need to add a test for it.
> new pipe: row join

- lib/upipe-framers/upipe_a52_framer.c
Depends on a pending pull request for bitstream.
> upipe_a52_framer: add channels attribute

- lib/upipe-framers/upipe_mpga_framer.c
Only for mp3, otherwise there are too many flow defs.
> mpgaf: use max octetrate for variable octetrate

- examples/ts_encrypt.c
- include/upipe-dvbcsa/upipe_dvbcsa_common.h
- lib/upipe-dvbcsa/upipe_dvbcsa_decrypt.c
This adds support for decrypting streams with odd/even keys.
Encryption is missing, we need a mechanism to toggle between odd/even keys (manual control ?)
> dvbcsa_decrypt: odd/even session words

- lib/upipe-ts/upipe_ts_demux.c
- lib/upipe-ts/upipe_ts_scte35_decoder.c
- lib/upipe-ts/upipe_ts_scte35_probe.c
Allow SCTE-35 detection before any event is received.
> upipe-ts: force sending SCTE-35 flow def

- lib/upipe-ts/upipe_ts_mux.c
Use inner urefcount structures to prevent upipe_ts_mux_psi_pid structure
to be freed before its inner pipes.
> ts_mux: fix refcounting of the psi pid structure

- examples/rist_tx.c
> rist_tx: fix variable shadowing

- include/upipe-filters/upipe_rtcp_fb_receiver.h
- include/upipe-filters/upipe_rtp_feedback.h
- lib/upipe-filters/upipe_rtcp_fb_receiver.c
- lib/upipe-filters/upipe_rtp_feedback.c
upipe_rtcpfb_get_stats
upipe_rtcpfb_reset_stats
upipe_rtpfb_reset_stats
upipe_rtpfb_get_rtt
> rist: add more commands for stats

- lib/upipe-blackmagic/upipe_blackmagic_extract_vanc.cpp
Used with sdi://0/video_bits=10
> bmd_vanc: extract vanc from 10-bits video

- lib/upipe-modules/upipe_dtsdi.c
- tests/Makefile.am
- tests/upipe_dtsdi_test.c
- tests/upipe_dtsdi_test.sh
I can't wait to see what Travis makes of this.
> fixes and a test for upipe-modules/dtsdi

- luajit/upipe.lua
Please comment. On the udict commit in particular because it is rather ugly.
The plane iterators are basically copied from the same foreach macros in the C headers.  The udict iterator is inspired by (or based on) udict_dump but without its switch statement.
> Luajit: add some iterator functions

- examples/extract_pic.c
Add filter format to convert unsupported formats.
> extract_pic: add filter format

- lib/upump-ev/upump_ev.c
- tests/upump_common_test.c
Calling upump_restart on inactive timers or on timers without repeat
value will reactivate the pump with the initial timeout value.
The old behavior of upump_restart:
- On active timer with a repeat value: the pump was restarted with
the repeat value.
- On active timer without a repeat value: the pump was deactivated
- On inactive timer: the pump remained inactive
The new behavior of upump_restart:
- On active timer with a repeat value: the pump is restarted with
the repeat value (same as before).
- On active timer without a repeat value: the pump is restarted with
the initial timeout value.
- On inactive timer: the pump is restarted with the initial timeout
value.
> upump: support restart on inactive timers

- lib/upipe-modules/upipe_rtp_pcm_pack.c
> upipe-modules/rtp_pcm_pack: add user options to control output size

- lib/upipe-modules/upipe_udp.c
I am not sure on where in the function this option should be set but it works for us in a brief test.
> upipe-modules/udp: add option to set multicast interface name, miface

- lib/upipe-modules/upipe_worker.c
Foward control commands to first then last inner if the control commands
have not been handled by the worker. It only works if a mutex was
provided to block inner pipes.
> upipe_worker: forward control commands to inner

- lib/upipe-modules/upipe_rtp_pcm_pack.c
Some fixes, improvements, and enhancements for the pipe.  Addresses the comments kierank made on #646
> Improvements for upipe_rtp_pcm_pack

- lib/upipe-modules/upipe_sync.c
> upipe_sync: Fix memory leak on glitchy video

- lib/upipe-av/ubuf_av.c
> ubuf_av: fix leaks on allocation failure

- lib/upipe-av/upipe_avfilter.c
Leave to the user the responsability to freeze the pipe before
configuring a new sub pipe or a new filter graph.
> upipe_avfilter: remove configuration eventfd pump

- include/upipe/uref_pic_flow.h
- include/upipe/uref_sound_flow.h
Comments welcome.  Especially about the descriptions.
> add two new attibutes

- configure.ac
- lib/upipe-ts/libupipe_ts.pc.in
Fixes #647 in my one test of it
> make upipe-ts pkgconfig file require gcrypt and tasn1 when needed

- lib/upipe-modules/upipe_audio_merge.c
- tests/upipe_audio_merge_test.c
We have some more things to come, such as interleaved support, but that might depend on another attribute being added first.
> upipe_audio_merge: upstreaming some improvements

- lib/upipe-blackmagic/ubuf_pic_blackmagic.cpp
Use the manager at allocation to prevent it from being released while
still referenced by the ubuf.
> ubuf_pic_bmd: prevent manager to be release

- lib/upipe-framers/upipe_mpga_framer.c
- tests/upipe_mpga_framer_test.c
Compute octetrate based on the output packet duration and size after
encapsulation for AAC streams so they take account of the possible
encapsulation overhead.
Use parsed octetrate for MPEG layers 1, 2 and 3 as the encapsulation
doesn't change.
> upipe_mpgaf: compute octetrate after encapsulation

- lib/upipe-framers/upipe_mpga_framer.c
Set the octet rate default value to 8kb/s and use it for flow format
negotiation.
This value will be used in the flow def before the first outputted
packet as the framer will force a need output probe event to negotiate
the output flow format.
At this time the real octet rate is unknown for AAC streams because the
flow format is not negotiated but some pipes need it in the flow def to
accept it.
These pipes may not accept the octet rate to decrease afterwards so it
must be as low as possible.
For AAC streams, octet rates are rounded up to a multiple of 8kb/s so
the lowest value possible is 8kb/s.
For MPEG layer 1, 2 and 3 streams, octet rates are parsed before the
probe event, so the default value will be overwritten.
> upipe_mpgaf: set default octet rate to 8kb/s

- examples/Makefile.am
- lib/upipe-av/Makefile.am
- tests/checkasm/Makefile.am
- tests/checkasm/sdi_input.c
- tests/checkasm/uyvy_input.c
Fixes #770 and something I let slip in #769
> guard bitstream use

- lib/upipe-framers/upipe_mpga_framer.c
When assuming the ADTS input is a SBR stream, the AudioSpecificConfig
extensionSamplingFrequency must be set accordingly.
> upipe_mpgaf: fix ADTS SBR streams sample rate

- lib/upipe-modules/upipe_rtp_pcm_unpack.c
If the pipe gets a flow_def saying the data has more channels than are
actually present then it can cause a 0 sample sized allocation and an
overwrite of the output buffer.
> upipe_rtp_pcm_unpack: prevent a 0-size alloc and overwrite

- lib/upipe-av/upipe_avformat_source.c
Check DTS prog on the output stream, not by a global value.
This fix a problem when the worker output multiple uref from a stream
then multiple uref from another.
For instance:
- Stream 1:
DTS 0
DTS 40
DTS 80
- Stream 2:
DTS 0  -> error
DTS 40 -> error
DTS 80 -> error
Fix: 6951f186cd2ddffccf6652726b88f8586b9e4cd2
> upipe_avfsrc: check DTS prog by streams

- lib/upipe-blackmagic/upipe_blackmagic_sink.cpp
Fixes high bitrate teletext streams
> upipe_blackmagic: Support segmented teletext ubufs

- lib/upipe-framers/upipe_mpga_framer.c
Overwrite bitrate with the computed value if any.
> upipe_mpgaf: overwrite bitrate

- lib/upipe-ts/upipe_ts_mux.c
This fixes PSI packets retention when a PSI with a lower PID is split in
multiple packets to comply with a constant bitrate (EITs for instance).
> upipe-ts: sort PSI by cr_sys date

- lib/upipe-modules/upipe_queue_source.c
Use a second refcount for the pumps as they may be used in another
thread (spoiler: it's meant to be).
Without this refcount, the pumps may use then release the external
refcount when dispatching (see upump_common_dispatch) after it has
reached zero in another thread.
Because urefcount_release is not thread safe in this case, there is 3
possible outcomes:
- nothing wrong because the refcount callback was already set to
NULL by the other thread (a.k.a. the planets are aligned)
- urefcount_release SEGV because refcount->cb was set to NULL by the
other thread after it was tested
- the refcount callback is called twice
The first problem here is that urefcounts are NOT thread safe if it's
allowed to use a reference which was already released. But it seems
there are some pipes which are …
> upipe_queue_source: fix race condition

- lib/upipe-ts/upipe_ts_encaps.c
- lib/upipe-ts/upipe_ts_mux.c
Force a mux update when an input program is removed.
> upipe-ts: fix mux update

- examples/ts_encrypt.c
- lib/upipe-dvbcsa/upipe_dvbcsa_decrypt.c
- lib/upipe-ts/upipe_ts_demux.c
config.h contains "#define UPIPE_HAVE_GCRYPT_H 1"
> Fix gcrypt options

- include/upipe/upipe_helper_output.h
- include/upipe/urequest.h
- lib/upipe-filters/upipe_filter_format.c
Override the wanted attributes and pass through the flow format request
to the downstream pipe. This lets the downstream pipe add some useful
attributes for the upstream pipe.
> upipe_filter_format: pass through the flow request

- lib/upipe-modules/upipe_blit.c
Provide desired aspect ratio (if any) for unsized flow format requests.
> upipe_blit: handle unsized aspect ratio

- lib/upipe-ts/upipe_ts_metadata_generator.c
Prevent the pipe from sending two consecutive packets when the pump is triggered just before the packet cr_sys.
> upipe_ts_mdg: fix double output

- lib/upipe-filters/upipe_filter_format.c
Drop buffered or input urefs when there is no input flow set or when the inner pipeline refuses the input flow. This prevents an invalid input flow from indefinitely blocking the pipe.
> upipe_ffmt: drop input when needed

- lib/upipe-freetype/upipe_freetype.c
Replace FTC_Manager_LookupFace with FTC_Manager_LookupSize to make sure face size is not NULL and will not be.
It seems that FTC_Manager_LookupFace does not guarantee that face->size will not be reset to NULL at any time but FTC_Manager_LookupSize does. Also make sure we remove the FaceID (font pointer) from the manager before we free it as recommended by FreeType documentation.
> upipe_freetype: fix potential SEGV

- lib/upipe-framers/upipe_h264_framer.c
Use debug messages before first SPS/PPS activation for early data.
> upipe_h264f: remove warnings at startup

- lib/upipe-filters/upipe_filter_format.c
Keep last provided flow format to prevent reconfiguration if the same flow format is provided again.
> upipe_ffmt: check if provided flow format changed
