Upipe/upipe

include/upipe-modules/upipe_file_sink.h, lib/upipe-modules/upipe_file_sink.c
This is useful if you need to perform ioctls on the file descriptor.
=> fsink: add GET_FD command

lib/upipe-av/upipe_avcodec_encode.c
Otherwise, libavcodec might print a warning for each encoded frame.
=> upipe-av: set frame dimensions for video encode

lib/upipe-ts/upipe_ts_decaps.c
Keep packets with this kind of invalid adaptation field because they are
commonly found in publicly available HLS streams.
=> upipe-ts: keep invalid packets with a 0-length payload

.travis.yml, configure.ac
Makes it easier to see warnings.
=> Enable automake silent rules by default

lib/upipe-av/upipe_avcodec_decode.c
Fixes crashes with fuzzed files
=> avcodec_decode: Use the frame width/height, not the context width/height

include/upipe-av/upipe_av_pixfmt.h, lib/upipe-av/upipe_avcodec_decode.c, lib/upipe-swscale/upipe_sws.c, lib/upipe-swscale/upipe_sws_thumbs.c, tests/upipe_sws_test.c
PixelFormat was renamed to AVPixelFormat as well.
This is visible now that the old versions have been removed
http://git.videolan.org/gitweb.cgi/ffmpeg.git/?a=commit;h=183db02a51a422568084b113a7571c845ca68622
=> avutil: Use AV_PIX_FMT rather than PIX_FMT

include/upipe-modules/Makefile.am, include/upipe-modules/upipe_rtp_reorder.h, lib/upipe-modules/Makefile.am, lib/upipe-modules/upipe_rtp_reorder.c
Modified-by: Rafaël Carré <funman@videolan.org>
Fix for upipe_rtp_reorder.c:358:17: error: ‘seqnum’ may be used
uninitialized in this function [-Werror=maybe-uninitialized]
Add missing upump_free()
=> Add support for RTP reordering (hitless switching)

lib/upipe-av/upipe_avcodec_decode.c, lib/upipe-av/upipe_avcodec_encode.c, tests/upipe_sws_test.c
Preparation for refcounted buffers
These changes were build-tested with FFmpeg 2.5
FFmpeg 2.4 doesn't build anymore:
error: ‘struct AVCodecContext’ has no member named ‘framerate’
error: ‘AV_CODEC_ID_APNG’ undeclared here (not in a function)
error: ‘AV_CODEC_ID_STL’ undeclared here (not in a function)
=> FFmpeg API update

include/upipe-av/upipe_av_pixfmt.h
It has to appear before yuv420p because it is a superset of it.
=> av_pixfmt: add yuva420p

lib/upipe-framers/upipe_h264_framer.c
Fixes assertion with fuzzed files.
=> framers/h264: Ignore ENDSEQ and ENDSTR NAL types

include/upipe-av/upipe_av_pixfmt.h, lib/upipe-av/upipe_avcodec_decode.c
It has to appear before yuv422p because it is a superset of it.
=> upipe-av: add yuva422p and convert to get_buffer2

include/upipe-ts/Makefile.am, include/upipe-ts/upipe_ts_pcr_interpolator.h, lib/upipe-ts/Makefile.am, lib/upipe-ts/upipe_ts_pcr_interpolator.c
This pipe will date TS packets without demuxing the whole TS.
Assuming a constant bitrate, the interval between 2 PCRs is used
to date packets between PCRs.
=> upipe_ts_pcr_interpolator: interpolate timestamps from PCRs

include/upipe-blackmagic/Makefile.am, include/upipe-framers/Makefile.am, include/upipe-modules/Makefile.am, include/upipe-ts/Makefile.am, lib/upipe-blackmagic/Makefile.am, lib/upipe-framers/Makefile.am, lib/upipe-modules/Makefile.am, lib/upipe-ts/Makefile.am
Adding a NULL entry at the end of the files list make every
line look the same with a trailing backslash.
This makes merging different trees easier when both trees have
added new files.
Do this for modules that changed recently
=> Makefile.am: make the list of source files easily mergeable

.travis.yml, configure.ac, include/Makefile.am, include/upipe-speexdsp/Makefile.am, include/upipe-speexdsp/upipe_speexdsp.h, lib/Makefile.am, lib/upipe-speexdsp/Makefile.am, lib/upipe-speexdsp/libupipe_speexdsp.pc.in, lib/upipe-speexdsp/upipe_speexdsp.c, tests/Makefile.am, tests/upipe_speexdsp_test.c
A few things that could be improved:
- make quality configurable (max quality is ok on CPU)
- use that module to resample at a fixed configurable rate (like swr for example), although not sure how to have the 2 modes.
=> upipe-speexdsp: resample audio to cancel drift rate

examples/mpthree2rtp.c, examples/udpmulticat.c, include/upipe-modules/upipe_udp_sink.h, include/upipe-modules/upipe_udp_source.h, lib/upipe-modules/upipe_udp_sink.c, lib/upipe-modules/upipe_udp_source.c, tests/upipe_udp_test.c
These commits let us do bi-directional UDP for NAT traversal
We can detect source address changes on udpsrc, give the udpsrc (which used bind()) fd to udpsink,
and set the remote peer address of udpsink.
=> bi-directional udp

include/upipe-modules/upipe_rtp_decaps.h, lib/upipe-modules/upipe_rtp_decaps.c, tests/upipe_rtp_decaps_test.c
Do not print a warning if that event was caught
=> rtp_decaps: custom probe event to signal packet loss

include/upipe/ubuf_block.h
This hunk was missed when sending Kieran's code.
This removes the slowness in h264 framer.
However since the code has changed since, please review and make sure it won't cause additional side effects.
ihavenoideawhatiamdoing.jpg
=> ubuf_block: fix 220fc2e5

lib/upipe-ts/upipe_ts_demux.c
upipe_{err,command,event}_str were uninitialized
This could cause a crash when sending them an unknown command
=> ts-demux: initialize upipe_mgr

lib/upipe-pthread/libupipe_pthread.pc.in
We need to know this when using a static upipe build, else we get:
libupipe_pthread.a(libupipe_pthread_la-uprobe_pthread_upump_mgr.o): undefined reference to symbol 'pthread_key_delete@@GLIBC_2.2.5'
We don't use autoconf's PTHREAD_LIBS because it hides -lpthread behind -pthread
=> upipe-pthread: depends on -lpthread

lib/upipe-amt/upipe_amt_source.c, lib/upipe-filters/upipe_filter_decode.c, lib/upipe-filters/upipe_filter_encode.c, lib/upipe-filters/upipe_filter_format.c, lib/upipe-modules/upipe_auto_source.c, lib/upipe-modules/upipe_rtp_source.c, lib/upipe-modules/upipe_sequential_source.c, lib/upipe-modules/upipe_transfer.c, lib/upipe-modules/upipe_worker_linear.c, lib/upipe-modules/upipe_worker_sink.c, lib/upipe-modules/upipe_worker_source.c, lib/upipe-ts/upipe_ts_demux.c, lib/upipe-ts/upipe_ts_mux.c
This ensures that upipe_{err,command,event}_str are initialized properly
=> always initialize upipe_mgr to 0

include/upipe/ubase.h
typeof is not recognized when using gcc -std=c11, use __typeof__ instead
=> ubase.h: C11 fix

lib/upipe-blackmagic/include/DeckLinkAPI.h, lib/upipe-blackmagic/include/DeckLinkAPIVersion.h, lib/upipe-blackmagic/upipe_blackmagic_source.cpp
Add an option to disable decklink mirroring, that is electrical wiring of the input to the output.
This helps when you're receiving and sending the same stream on the same card, else you are
not sure if your middle man is running properly.
=> Bmd mirror

lib/upipe-modules/upipe_m3u_reader.c
Allow whitespace before and after comma in an attibute list.
=> upipe_m3u_reader: allow whitespace in attribute list

lib/upipe/libupipe.pc.in
libupipe depends on libm, we need to know this if we link to a static libupipe
=> fix pkg-config --static --libs libupipe

lib/upipe/uprobe_stdio.c, lib/upipe/uprobe_stdio_color.c
sprintf will insert terminating '\0'
=> uprobe_stdio*: remove memset

lib/upipe-modules/upipe_http_source.c
Make sure to send a zero-length uref with end attribute set in case of
error or when connection is closed.
=> upipe_http_source: send uref with end attribute

include/upipe-modules/upipe_delay.h, lib/upipe-modules/upipe_delay.c, tests/upipe_delay_test.c, tests/upipe_file_test.c, tests/upipe_seq_src_test.c
uref_clock_date_add already handles int64_t
=> upipe_delay: supports negative delays

include/upipe/uref_sound_flow.h, lib/upipe-av/upipe_avcodec_decode.c
This is set for example by the libavcodec s302m decoder
=> upipe-av: include raw bits per sample in audio flow if known

configure.ac
Use ./configure --enable-luajit to explicitly enable luajit binding
build.
=> luajit: disable build by default

lib/upipe-framers/upipe_h264_framer.c
Fixes 9ec345663 with some weird streams
=> h264_framer: do not calculate DTS if already present

lib/upipe-av/upipe_avcodec_decode.c
FFmpeg h264 decoder won't reinit framerate if it's the only thing that changes in the stream
=> upipe-av: prefer input framerate if set

include/upipe/udict.h
Check if destination pointer is not NULL. Don't treat NULL pointer as an
error so you can check for udict key presence. For instance use
uref_flow_get_def(flow_def, NULL) to check for flow definition input.
=> udict: fix udict_get_* with empty pointer

include/upipe/upipe.h
If we don't handle the request the args might be used again
=> upipe_control_provide_request: copy args before using them

lib/upipe-av/upipe_avformat_sink.c, lib/upipe-filters/upipe_filter_vanc.c, lib/upipe-hls/upipe_hls_master.c, lib/upipe-hls/upipe_hls_playlist.c, lib/upipe-modules/upipe_audio_split.c, lib/upipe-modules/upipe_file_sink.c, lib/upipe-modules/upipe_null.c, lib/upipe-modules/upipe_rtp_h264.c, lib/upipe-modules/upipe_rtp_reorder.c, lib/upipe-modules/upipe_stream_switcher.c, lib/upipe-modules/upipe_udp_sink.c, lib/upipe-osx/upipe_osx_audioqueue_sink.c, lib/upipe-ts/upipe_ts_demux.c, lib/upipe-ts/upipe_ts_scte35_probe.c, lib/upipe-ts/upipe_ts_tdt_decoder.c
Make sure to handle register/unregister request once if
upipe_control_provide_request return UBASE_ERR_UNHANDLED.
=> upipe_control_provide_request: handle (un)register request once

Makefile.am
Use EXTRA_DIST instead of dist_pkgdata_DATA to prevent installing the
mkdoc files to the host filesystem.
=> doc: don't install mkdoc sources

examples/Makefile.am, lib/Makefile.am
The v210 tests still depend on avutil headers.  I don't know whether you think it is good to build something that you cannot test.
=> small build system adjustments

lib/upipe-blackmagic/upipe_blackmagic_sink.cpp
HD-SDI streams can have up to 5 teletext packets per line,
according to Free TV Australia Operational Practice OP-47
=> bmd_sink: fix condition reversing

configure.ac, tests/Makefile.am, tests/checkasm/Makefile.am, tests/checkasm/checkasm.c, tests/checkasm/checkasm.h, tests/checkasm/checkasm_x86.asm, tests/checkasm/sdidec.c, tests/checkasm/sdienc.c, tests/checkasm/timer.h, tests/checkasm/timer_x86.h, tests/checkasm/v210dec.c, tests/checkasm/v210enc.c
For those unaware this utility is a great platform on which to test SIMD functions.  It iterates over a list of functions and calls each after forcing CPU feature flags to be each one available on the host.  Each function in the list called is a specially written function that: sets up data structures needed to run a reference and tested functions; creates input data; runs both the reference and tested functions; checks whether the output is correct, usually whether it is identical to the reference output; finally it reports the status to the main program.  It also provides an option to benchmark the functions
This PR is intended to get comments on adopting this into Upipe.
=> Copy FFmpeg's checkasm test utility

lib/upipe-hbrmt/sdidec.asm, lib/upipe-hbrmt/sdidec.c, lib/upipe-hbrmt/sdidec.h, lib/upipe-hbrmt/sdienc.asm, lib/upipe-hbrmt/sdienc.c, lib/upipe-hbrmt/sdienc.h, lib/upipe-hbrmt/upipe_pack10bit.c, lib/upipe-hbrmt/upipe_unpack10bit.c, lib/upipe-v210/upipe_v210enc.c, lib/upipe-v210/v210enc.asm, lib/upipe-v210/v210enc.c, lib/upipe-v210/v210enc.h, tests/checkasm/sdidec.c, tests/checkasm/sdienc.c, tests/checkasm/v210enc.c
First harmonize function names in the form X_to_Y.  Next remove an unused function I saw while doing that.  Finally simplify odd if-else-if-if block for choosing functions.
=> Improve assembly functions

lib/upipe/ubuf_pic_mem.c, lib/upipe/ubuf_sound_mem.c
Make sure we don't reuse a manager with no alignment.
=> ubuf_mem: fix alignment check

tests/checkasm/Makefile.am, tests/checkasm/sdienc.c
The functions we need are not visible when building shared libraries on
Linux or ELF causng a linking error.
=> checkasm: link objects directly

include/upipe/upipe.h
Don't release probe in upipe_*_alloc_output because upipe_*_alloc is
responsible for it if it fails.
=> upipe: fix upipe_*_alloc_output double release

lib/upipe-filters/upipe_rtcp_fb_receiver.c, lib/upipe-filters/upipe_rtp_feedback.c
=> rtcp_fb, rtpfb: do not reuse flow_def in UBUF_MGR

lib/upipe-av/upipe_avcodec_decode.c
Apparently it means infinity or until next subpicture replaces it
Reference: https://ffmpeg.org/pipermail/ffmpeg-devel/2018-May/229341.html
=> avcodec: handle subtitle duration UINT32_MAX

include/upipe/upump.h, include/upipe/upump_common.h, lib/upipe/upump_common.c, lib/upump-ecore/upump_ecore.c, lib/upump-ev/upump_ev.c, tests/upump_common_test.c
Add upump_restart for timer pumps to reset the timeout.
=> upump: add restart control for timers

lib/upipe-ts/upipe_rtp_fec.c
We need the RTCP packets if next pipe is doing arq
We just avoid doing FEC on this stream
Note that this commit is not enough, when doing ARQ we also need to pass through the retransmits,
which have a different payload type.
Copy/pasting IRC:
16:40 < funman> we have 5 streams
16:41 < funman> #1 main rtp (PT 33 since it's mpeg-ts)
16:41 < funman> #2 & 3 : row / column rtp, on 2 other ports
16:41 < funman> #4 RTCP (see above patch)
16:41 < funman> #5 retransmits, using PT 97
16:42 < funman> so fec needs to let RTCP (detectable) and retransmits (not detectable without an SDP) go through
16:43 < funman> not sure where else we do this but we could count packets with a different PT and reset if e.g. >5
16:43 < funman> so once we see PT 33, let everything else go through
16:43 < funman> and if …
=> fec: forward RTCP to next pipe

lib/upipe-x265/upipe_x265.c
Since x265 version 2.8:
x265.h:1880:5: error: 'ENABLE_LIBVMAF' is not defined, evaluates
to 0 [-Werror,-Wundef]
=> upipe-x265: work around x265.h undef warning

lib/upipe-modules/upipe_s337_encaps.c
Tested-by: Kieran Kunhya <kierank@obe.tv>
=> s337 encaps: handle odd sized ubuf segments

examples/fec.c, include/upipe-ts/upipe_rtp_fec.h, lib/upipe-ts/upipe_rtp_fec.c
If a packet has a payload type different from the first packet,
forward it to the next pipe immediately.
This lets us include not only RTCP but also retransmits which are
multiplexed together with the original RTP stream
=> fec: check payload type

lib/upipe-netmap/Makefile.am
As title says.  Now that I think about it, is there a NETMAP_CFLAGS that should be added too?
=> upipe-netmap: add BITSTREAM_CFLAGS

lib/upipe-hls/upipe_hls_playlist.c
Start live playlist at the end but leaving at least 3 * target duration.
From RFC 8216 section 6.3.3
(https://tools.ietf.org/html/rfc8216#section-6.3.3): "[...] the client
SHOULD NOT choose a segment that starts less than three target durations
from the end of the Playlist file."
Is considered live playlist: playlist without type or with type EVENT
and no EXT-X-ENDLIST tag.
See: https://tools.ietf.org/html/rfc8216#section-4.3.3.5
=> upipe-hls: start at end of live playlist

lib/upipe-x265/upipe_x265.c
Since x265 version 2.9:
x265.h:34:5: error: '_MSC_VER' is not defined, evaluates to 0
x265.h:175:5: error: 'X265_DEPTH' is not defined, evaluates to 0
=> upipe-x265: work around x265.h undef warnings

lib/upipe-av/Makefile.am
Explicitely create a dummy file that Makefile can include before
generating the real version.
Also create the .deps dir.
This is needed on Ubuntu 18.10 / automake 1.16
=> upipe_av_codecs.h: fix dependencies generation

include/upipe/upipe.h, lib/upipe-av/upipe_avformat_sink.c, luajit/Makefile.in
Allocating an avfsink subpipe adds a stream to the avformat context,
which cannot be removed afterwards, so we need to be able to check that
a given flow def is supported before allocating the subpipe.
=> upipe-av: add avfsink mgr command for checking flow defs

lib/upipe/upipe_dump.c
Helpful for finding missing upipe_release.
=> upipe_dump: print refcounts

examples/rist_rx.c
We already do the same thing in rist_tx
This avoid killing the entire RTCP channel in case of spurious error
=> rist_rx: restart RTCP socket in case of error

lib/upipe-framers/upipe_mpga_framer.c
Add a trailing zero for variable frame length when the frame length is
multiple of 255.
=> upipe_mpga_framer: fix LOAS/LATM encaps

lib/upipe-modules/upipe_udp_sink.c, lib/upipe-modules/upipe_udp_source.c
fds must be removed from the epoll set before closing, otherwise a race
condition can trigger when a new fd is created with the same value as
the closed one.
=> upipe_udp: fix upump fd close race condition

lib/upipe-dvb/upipe_dvbsrc.c
Fixes compilation warning from clang 8.
=> upipe-dvb: add missing printf attribute

lib/upipe-framers/upipe_mpga_framer.c
Broken by 026ef0879b537c1f98daeb3a7c6d9509ce9cb1c5
=> upipe_mpga_framer: fix ADTS asc_base_aot value

lib/upipe-modules/upipe_sync.c
Do not drop frames when that happens.  Do not try to wait using that
time.  Do not try to adjust PTS using that time.
Perhaps there is a better way to address this.  However this change has let me get output when using my clock and sink.
I have a cosmetic question.  What is Upipe's opinion on conditional ternary operators?  The if-else expressions could be shortened to `(now == UINT64_MAX) ? ticks_per_frame : pts - now`
=> upipe-modules: make upipe_sync catch UINT64_MAX values from uclock_now

include/upipe/ubase.h
Also fix alignment of return statement.
=> include/upipe/ubase: fix doxy comment for ubase_clip

lib/upipe-modules/upipe_void_source.c
This change addresses the issue I was experiencing but I am not sure how "correct" it is.  Please comment if you think there's a better way to handle this.
=> upipe-modules: prevent an infinite loop in voidsrc

include/upipe-modules/Makefile.am, include/upipe-modules/upipe_audio_merge.h, include/upipe/ubase.h, lib/upipe-modules/Makefile.am, lib/upipe-modules/upipe_audio_merge.c, tests/Makefile.am, tests/upipe_audio_merge_test.c
PR #602 rebased and all relevant commits squashed together.  Did you want to keep any of the other commit messages?  I used the fixup option which drops the messages from the squashed commits.  I didn't think they looked useful.
=> rebased and squashed audio_merge

lib/upipe-ebur128/upipe_ebur128.c
If rate is zero, libebur128 state allocation fails and returns NULL.
Then the next input buffer will trigger a SEGV.
=> upipe-ebur128: check input rate value

lib/upipe-framers/upipe_a52_framer.c
Fix conditional jump on uninitialized value from valgrind.
=> upipe_a52_framer: fix valgrind warning

include/upipe-ts/upipe_ts.h, include/upipe/ubase.h, lib/upipe-ts/upipe_ts_mux.c, lib/upipe-ts/upipe_ts_psi_generator.c
This commit depends on bitstream commit
8232e05cbe1258745bace6094540adb0cd392dad.
=> upipe-ts: fix AC-3 when conformance is ATSC

lib/upipe-ts/upipe_ts_demux.c
If last_pcr is greater than TS_CLOCK_MAX the loop will never end.
=> upipe_ts_demux: fix potential infinite loop

lib/upipe/uprobe_select_flows.c
Don't release the sub probe when the sub pipe ends. If the sub probe is
released when the source ends it will prevent the next SPLIT_UPDATE to
select a new pipe because need_update will be false.
=> uprobe_selflow: keep sub probe when source end

include/upipe/upipe_helper_bin_input.h, include/upipe/upipe_helper_iconv.h, include/upipe/uprobe_helper_alloc.h
This was already done for some of the upipe_helper headers, this does it for the rest.
I confirmed that upipe compiles, that "make check" reports all tests are still successful, and that this change fixes including from C++.
=> Fixed C++ malloc compatibility in public headers

lib/upipe-filters/upipe_filter_encode.c
The uninitialized bit_depth could trigger a failing control on non-x265
inner pipes.
=> upipe_filter_encode: fix random set_flow_def failure

lib/upipe-filters/upipe_audio_max.c, tests/upipe_audio_max_test.c
Avoid changing INT32_MAX value from 2147483647 to 2147483648 due to
implicit float conversion. Use double instead.
=> upipe_audio_max: avoid implicit float conversion

lib/upipe-framers/upipe_h264_framer.c
Fix invalid behaviours on a Adobe Premiere TS file
=> upipe_h264f: fix invalid behaviours

lib/upipe-modules/upipe_audio_merge.c
Sending these two patches upstream.  The first just removes the unused upump code.  The second is either a fix or a workaround for a crash we saw when using the pipe.
I don't think we ever discovered the root cause of the issue in our software but the effect was using the stored flow_def after it was freed causing a segfault.
=> upipe_audio_merge: small fix and cleanup

lib/upipe-speexdsp/upipe_speexdsp.c
Drop input urefs if it doesn't exist.
On IRC I asked about the following problem: "I need to deport upipe_speexdsp to a worker thread but it doesn't get a ubuf_mgr before trying to create a ubuf with it which causes an assert.  What is the preferred way to have the pipe check whether it is ready to handle input urefs?"
This is what I quickly put together for our usage because I wasn't sure how else to handle it.
=> upipe_speexdsp: check that the ubuf_mgr exists before using it

lib/upipe-framers/upipe_mpga_framer.c
Reset flow_def_requested when a new flow format is provided as it is
used to check if the pipe can handle new urefs. Because the provided
flow format will unset the ubuf manager before requiring a new one, the
pipe must wait for the new ubuf manager before handling new urefs.
=> upipe_mpgaf: fix potential assert

lib/upipe-ts/upipe_ts_encaps.c
Flush the rest of the access unit to prevent future splice to assert on
the access unit size.
=> upipe_ts_encaps: fix a potential assert

lib/upipe-blackmagic/upipe_blackmagic_source.cpp
Alignment may be used by other pipes to enable optimization (v210dec for
instance).
=> upipe_bmdsrc: set format alignment

include/upipe-ts/upipe_ts_mux.h, lib/upipe-ts/upipe_ts_mux.c
Add a maximum octetrate setter control command to prevent invalid input
flow format from increasing the mux octetrate over a configured value.
=> upipe_ts_mux: add maximum octetrate setter command

lib/upipe-framers/upipe_h265_framer.c
Skip invalid slice data without discarding the entire access unit.
=> upipe_h265f: skip invalid slice data

lib/upipe-ts/upipe_ts_demux.c
Don't reset the PCR on discontinuities if the delta with the previous
value is below the tolerance.
=> upipe_ts_demux: ignore discontinuity flag for PCR

configure.ac, include/upipe/uatomic.h
Reduce false positives with gcc's thread sanitizer.
=> uatomic: replace legacy __sync builtins with __atomic

lib/upipe-av/upipe_avfilter.c
Also set the frame pts and duration for input uref with ubuf_av as they
may be modified by previous pipes.
=> upipe_avfilter: set pts and duration for avframes

lib/upipe-modules/upipe_http_source.c
Throw an error when connection failed.
=> upipe_http_source: throw an error when needed

include/upipe-av/upipe_av_pixfmt.h, include/upipe-modules/upipe_blit.h, include/upipe/ubuf_pic.h, include/upipe/uref_pic.h, include/upipe/uref_pic_flow_formats.h, lib/upipe-modules/upipe_blit.c
A slightly experimental patch set for supporting a 10-bit alpha blend in upipe_blit.  It does work for me.
Possibly a mix of semi-related changes because I needed to get our program to support a particular use case.  I needed to get it to convert and scale SD rgba into HD yuva422p10le and correctly draw that onto the main yuv422p10le video.
One concern I have is the performance.  While testing I still had a bug which caused it to enter the wrong branch: the "on/off blending" branch with the divide by 0x3ff.  It caused the function to be the most costly function in the whole program.  The only goog was the compiler managed to optimize it into a multiply and right shift.  Fixing the bug so it didn't enter that branch gives much better performance.  I can't imagine how slow the true blend …
=> 10-bit alpha blend support for upipe_blit

lib/upipe-ts/upipe_ts_mux.c
Broken in 1ccd0066bfed3315bd181985f7a22ca62a92b011.
=> upipe_ts_mux: restore dvb subtitle support

lib/upipe-ts/upipe_ts_demux.c, tests/upipe_ts_demux_test.c
Update the highest timestamp after the framers as it might be interpolated.
=> upipe_ts_demux: update highest timestamp

lib/upipe-framers/upipe_telx_framer.c
Send new flow def only when octetrate increase to prevent octetrate from bouncing up and down.
=> upipe_telxf: stabilize octetrate

lib/upipe-framers/upipe_h264_framer.c
Issues found by h26forge - github.com/h26forge/h26forge
=> upipe_h264_framer: Fix valgrind warnings on fuzzed files

lib/upipe/udict_inline.c, tests/udict_inline_test.c
Remove udict optimization when setting an existing string attribute with a smaller content. This optimization may cause issues when comparing the udict as the attribute size may be different for the same content.
=> Fix udict comparaison

lib/upipe-ts/upipe_ts_metadata_generator.c
This patch prevent (very) late input from sending multiple late metadata when starting.
=> upipe_ts_metadata_generator: fix late input

tests/upipe_glx_sink_test.c
After the cube rendering was split in 6204a296c this was never updated.
=> tests: fix upipe_glx_sink_test

lib/upipe-filters/upipe_filter_format.c
Prevent assert when swscale allocation fails and there is some flags to set.
=> upipe-ffmt: prevent assert on allocation error

lib/upipe-av/upipe_avcodec_decode.c
FFmpeg 6 requires a threadsafe get_buffer2 callback, so we must use the copy-opaque codec flag instead of the get_buffer2 callback to transfer each incoming uref to the corresponding decoded AVFrame.
=> upipe_avcdec: use copy-opaque codec flag for ffmpeg 6

lib/upipe/uuri.c, tests/uuri_test.c
Allow calling uuri_escape() with null buffer.
=> uuri: fix undefined behaviour

include/upipe/ustring.h
Allow calling ustring_sub() with null string.
=> ustring: fix undefined behaviour

lib/upipe-av/upipe_avfilter.c
AVBufferSrcParameters.color_range requires FFmpeg 7.0.
=> upipe-av: fix compilation with previous ffmpeg versions

lib/upipe-ts/upipe_ts_demux.c
Delete invalid DTS orig so we can detect it and possibly fix it afterwards (in telx_probe for instance).
=> upipe_ts_demux: delete invalid DTS orig

lib/upipe-framers/upipe_h265_framer.c
nuh_temporal_id_plus1 cannot be zero
=> upipe-framers/h265: Fix AUD generation

lib/upipe-blackmagic/upipe_blackmagic_sink.cpp
Debugging a problem here and noticed a couple of uninitialized members.
=> upipe_blackmagic_sink: initialize more private struct members

lib/upipe-ts/upipe_ts_demux.c
This reverts commit acd8412069e6a040eb7a68c3be895412c415915c.
Keep DTS orig because we may need it to fix invalid DTS. Use DTS prog to check if the DTS was considered valid by the demux.
=> upipe_ts_demux: check prog to detect invalid DTS

lib/upipe-ts/upipe_ts_split.c
Prevent SEGV when the output is released during the loop.
=> upipe_ts_split: fix SEGV when an output is released during the loop

lib/upipe-ts/upipe_ts_demux.c
Prevent input DTS tolerance from overflowing the maximum input DTS delay.
=> upipe_ts_demux: fix potential tolerance overflow

lib/upipe-av/upipe_avcodec_decode.c
frame->duration comes from pkt->duration which might be a field or a frame depending on the pic structure, so it cannot be used reliably for now.
=> upipe_avcdec: fix video frame duration

lib/upipe-framers/upipe_mpgv_framer.c
Prevent sequence header duplication when using complete_input flag.
=> upipe_mpgvf: prevent sequence header duplication

lib/upipe-modules/upipe_row_join.c, lib/upipe-modules/upipe_rtp_pcm_pack.c, lib/upipe-modules/upipe_separate_fields.c
A small FYI.
I found these files by searching for all files which matched 'UPIPE_HELPER|upipe_throw_ready|upipe_throw_dead' meaning they were probably the main files for pipes.  Then I filtered that list for files which did not match 'upipe_throw_dead' or 'upipe_throw_ready'.
Specifically I ran these commands:
```
vim $(rg --files-without-match upipe_throw_ready -- $(rg -l 'UPIPE_HELPER|upipe_throw_ready|upipe_throw_dead' lib/))
vim $(rg --files-without-match upipe_throw_dead -- $(rg -l 'UPIPE_HELPER|upipe_throw_ready|upipe_throw_dead' lib/))
```
=> upipe-modules: make all pipes throw ready and dead events

lib/upipe-ts/upipe_ts_demux.c
Set TOT decoder output to a null pipe to prevent debug logs for each totd output.
=> upipe_ts_demux: decrease totd verbosity

lib/upipe-av/upipe_avcodec_decode.c
Caller can use upipe_set_option("extra_hw_frames") to set a custom hw frame count if needed.
=> upipe_avcdec: don't use hardcoded extra hw frames

lib/upipe-modules/upipe_blit.c
Prevent flow format negotiation when nothing change.
=> upipe_blit: prevent useless flow format provide

lib/upipe-av/upipe_av_internal.h, lib/upipe-av/upipe_avfilter.c
Caller can use the "extra_hw_frames" filter option to set a custom hw frame count if needed.
=> upipe_avfilter: don't use hardcoded extra hw frames

lib/upipe-hls/upipe_hls_audio.c
fix: d27a083d9ed00e2016f939cfb35ace36c2766f26
=> upipe-hls: fix audio PCR interval tolerance

lib/upipe-framers/upipe_h264_framer.c
The sei_rbsp structure may contain multiple sei_message structures, but only the first one was parsed.
=> upipe_h264f: fix SEI parsing
